### PR TITLE
useSuperTokensFromNextJs

### PR DESCRIPTION
**Pull request by NkxxkN**
Expose a general middleware that can be used with any methods:

```js
import {superTokensNextWrapper} from "supertokens-node/nextjs";

// Example for Middleware
superTokensNextWrapper(async (next) => {
  return SuperTokens.middleware(request, response, next)
}, request, response);

// Example for Verify Session
superTokensNextWrapper(async (next) => {
  return SuperTokens.verifySession(request, response, next)
}, request, response);
```

Used in demo repo https://github.com/supertokens/supertokens-nextjs-demo/pull/5

### CODE REVIEW

**Comment by NkxxkN** [comment]
Rename from `useSuperTokensFromNextJs` to `superTokensNextWrapper`.

The reason is that `eslint(react-hooks/rules-of-hooks)` prevents using any functions starting with `use` (such as `useState`, `useEffect` etc...) from some places. 

`useX` is a reserved prefix by React hooks :/ 

image

**Comment by rishabhpoddar** [comment]
Due to the rename, your first comment will change to
```js
import {superTokensNextWrapper} from "supertokens-node/nextjs";

// Example for Middleware
superTokensNextWrapper(async (next) => {
  return SuperTokens.middleware(request, response, next)
}, request, response);

// Example for Verify Session
superTokensNextWrapper(async (next) => {
  return SuperTokens.verifySession(request, response, next)
}, request, response);
```

Right? If yes, please feel free to merge. Also, we need to make changes to the docs for this.

**Comment by NkxxkN** [comment]
Updated my comment. There will be changes to the docs.

The code snippets in the docs should be replaced with the content of that PR https://github.com/supertokens/supertokens-nextjs-demo/pull/5.
They are hard to maintain though. I think we should encourage to clone the repo, and in case they don't, we should link to the files from the repo so that we do not have to make doc updates every time something changes.

**Comment by rishabhpoddar** [comment]
> docs should be replaced with the content of that PR

I don't think users will like to go through lots of code in a demo app to learn how to use us with NextJS. There will need to be a page in the docs for it for sure. The demo app probably only helps as a reference...

**Pull request merged**
