### PR TITLE
3.2.nextjs

### PR DESCRIPTION
**Pull request by NkxxkN**
- Add `supertokensMiddleware` |
- Update to changelog
- Bump to 3.2

### CODE REVIEW

**Comment by NkxxkN** [comment]
TODO: After this one is released https://github.com/supertokens/supertokens-nextjs-demo/pull/1

**Comment by NkxxkN** [comment]
Fixes https://github.com/supertokens/supertokens-node/issues/56

**Comment by rishabhpoddar** [comment]
- We need to export the next js middleware as a default and a non default export (just like other functions exposed).
- From a file structure point of view, I prefer not having `nextjs.ts` inside a helpers folder. It should be in the root of the `ts` folder imo. The reason is that it's not a helper to anything in the source code. It's a function that the user uses directly.

**Comment by rishabhpoddar** [comment]
We also need to create a new version of the docs for supertokens-node -> 3.2.X. But feel free to commit this please. Looks good to me.

**Pull request merged**
