### PR TITLE
[WIP] feat: improve form validation

### PR DESCRIPTION
**Pull request by akashrajum7**
## Summary of change

This PR aims to improve the form field validation in emailpassword to allow for optional form fields to be truly optional and not have to send empty values. It looks like the rest of the recipes use the UserMetadata recipe to store extra information.

## Related issues

- https://github.com/supertokens/supertokens-node/issues/300
- https://github.com/supertokens/supertokens-auth-react/issues/638

## Test Plan

Added a test case to check the functionality of optional fields missing in the payload does not result in an error

## Documentation changes

Not sure which section of the docs talks about the behaviour of optional fields currently, can update there once this implementation is completed

## Checklist for important updates

-   [x] Changelog has been updated
-   [x] Changes to the version if needed
    -   In `package.json`
    -   In `package-lock.json`
    -   In `lib/ts/version.ts`
-   [x] Had run `npm run build-pretty`
-   [x] Had installed and ran the pre-commit hook
-   [ ] Issue this PR against the latest non-released version branch.
    -   To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch --all`) whose `X.Y` is greater than the latest released tag.
    -   If no such branch exists, then create one from the latest released branch.

## Remaining TODOs for this PR

-   [ ] Get clarity on what it means to "improve error message" for missing form fields

### CODE REVIEW

**Comment by akashrajum7** [comment]
@rishabhpoddar - Need your inputs here:

1. What does it mean by "improve error message"? An example would be super helpful.
2. Does this approach of only validating optional fields when present sound right to you?

Thanks.

**Review by rishabhpoddar — APPROVED** [review]

**Comment by rishabhpoddar** [comment]
Hey @akashrajum7 there are two tests that are failing due to the changes made here: https://app.circleci.com/pipelines/github/supertokens/supertokens-node/5985/workflows/cfe50d90-2d11-4f6d-bf95-180345c1235c/jobs/3363

**Comment by akashrajum7** [comment]
> Hey @akashrajum7 there are two tests that are failing due to the changes made here: https://app.circleci.com/pipelines/github/supertokens/supertokens-node/5985/workflows/cfe50d90-2d11-4f6d-bf95-180345c1235c/jobs/3363

Last I ran this locally, everything went through fine, let me check again and open a new PR in case any changes are required, thanks.

**Comment by rishabhpoddar** [comment]
@akashrajum7 we are doing the fix on our end now, since we have to do a release soon, and this is blocking our release.

**Comment by akashrajum7** [comment]
@rishabhpoddar Sure, thanks. Would be nice if there was a pre-check on the test cases before the merge passes.

**Pull request merged**
